on: workflow_dispatch

jobs:
  release-artifact:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: get repo contents
        uses: actions/checkout@v5

      - name: install node dependency
        run: npm install

      - name: build
        run: npm run build

      - name: create release artifact
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/**
          body: "Release artifact built from latest code."
          tag_name: "v0.0.0-release-artifact"
        # uses: actions/upload-artifact@v5
        # with:
        #   name: release-artifact
        #   path: ./dist
