on: push

permissions:
  contents: write

jobs:
  npm-build:
    runs-on: ubuntu-latest

    steps:
      - name: get repo contents
        uses: actions/checkout@v5
      
      - name: install node dependency & build
        run: 
          npm install
          npm run build
      - name: check output result
        run:
          ls
          

      
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: github-pages
          folder: ./dist

